-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    userid serial,
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
	email character varying(320) NOT NULL,
    isAdmin boolean NOT NULL DEFAULT false,
    createdat timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isactive boolean NOT NULL DEFAULT true,
    PRIMARY KEY (userid),
    CONSTRAINT username_unique UNIQUE (username),
	CONSTRAINT email_unique UNIQUE (email)
);